fix: Claims Retrieval Issue in SqlIdentityHubStore Due to Missing pay…
eclipse-edc/IdentityHub pull request #108
Opened 2023-06-26 12:44 UTC by konrad1adamczyk

…loadFormat #107

## What this PR changes/adds

_Briefly describe WHAT your pr changes, which features it adds/modifies._

## Why it does that

_Briefly state why the change was necessary._

## Further notes

_List other areas of code that have changed but are not necessarily linked to the main feature. This could be method
signature changes, package declarations, bugs that were encountered and were fixed inline, etc._

## Linked Issue(s)

Closes # <-- _insert Issue number if one exists_

## Checklist

- [ ] added appropriate tests?
- [ ] performed checkstyle check locally?
- [ ] added/updated copyright headers?
- [ ] documented public classes/methods?
- [ ] added/updated relevant documentation?
- [ ] added relevant details to the changelog? (_skip with label `no-changelog`_)
- [ ] formatted title correctly? (_take a look at the [CONTRIBUTING](https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/blob/main/CONTRIBUTING.md#submit-a-pull-request) and [styleguide](https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/blob/main/styleguide.md) for details_)

2023-06-27 07:06 UTC, paullatzelsperger requested changes

2023-06-27 07:06 UTC, paullatzelsperger commented on extensions/store/sql/identity-hub-store-sql/src/main/java/org/eclipse/edc/identityhub/store/sql/SqlIdentityHubStore.java
> +                .payloadFormat(resultSet.getString(statements.getPayloadFormatColumn()))
could you add a test for this, to guard against regression?

2023-06-27 07:08 UTC, paullatzelsperger commented
thanks for the fix, but please familiarize yourself with our [pr etiquette](https://github.com/eclipse-edc/Connector/blob/main/pr_etiquette.md), which states that raising PRs without associated issues is not allowed. After having raised an issue, it should go through triage before any work can happen.

2023-06-28 07:26 UTC, bscholtes1A commented
LGTM, I'll approve when unit-test is added.

2023-07-04 13:46 UTC, paullatzelsperger commented
@konrad1adamczyk postgres tests are failing. can you see what's going on there?

2023-07-05 05:41 UTC, konrad1adamczyk commented
yes I see it here, on my local machine it was passing, I will fix

2023-07-07 05:24 UTC, paullatzelsperger commented
checkstyle is failing due to a missing license header.

2023-07-07 05:35 UTC, paullatzelsperger requested changes
Please familiarize yourself with our [coding principles](https://github.com/eclipse-edc/Connector/blob/main/docs/developer/architecture/coding-principles.md) and [testing rules](https://github.com/eclipse-edc/Connector/blob/main/docs/developer/testing.md). 

Maybe you could add unit and integration tests (using Testcontainers) for the SqlIdentityHubStore, it would a) be a good way to familiarize yourself with the codebase and our principles, and b) would be more comprehensive test. Unfortunately we cannot accept this PR as-is.

2023-07-07 05:35 UTC, paullatzelsperger commented on extensions/store/sql/identity-hub-store-sql/src/test/java/org/eclipse/edc/identityhub/store/sql/SqlIdentityHubStoreTest.java
> +        IdentityHubRecord result = sqlIdentityHubStore.parse(resultSet);
user `var`

2023-07-07 05:35 UTC, paullatzelsperger commented on extensions/store/sql/identity-hub-store-sql/src/test/java/org/eclipse/edc/identityhub/store/sql/SqlIdentityHubStoreTest.java
> +        assertEquals("123", result.getId());
please use `assertJ` assertions

2023-07-07 05:35 UTC, paullatzelsperger commented on extensions/store/sql/identity-hub-store-sql/src/main/java/org/eclipse/edc/identityhub/store/sql/SqlIdentityHubStore.java
> +    IdentityHubRecord parse(ResultSet resultSet) throws SQLException {
this method is `private`. making methods `package-private` or `protected` simply to be able to test them is an anti-pattern.

2023-07-07 05:35 UTC, paullatzelsperger commented on extensions/store/sql/identity-hub-store-sql/src/test/java/org/eclipse/edc/identityhub/store/sql/SqlIdentityHubStoreTest.java
> +public class SqlIdentityHubStoreTest {
this is not a sufficient test for the `SqlIdentityHubStore`.

2023-07-07 05:35 UTC, paullatzelsperger commented on extensions/store/sql/identity-hub-store-sql/src/test/java/org/eclipse/edc/identityhub/store/sql/SqlIdentityHubStoreTest.java
> +        MockitoAnnotations.openMocks(this);
not how we do mocks. please use the static `mock()` method. also, please use static imports.

2023-07-11 12:04 UTC, bscholtes1A commented
handled through #112

2023-07-11 12:04 UTC, closed without merging